#pragma once
#include "api.h"
#include "cddbinterface.h"
#include "main.h"
#include "../winamp/wa_ipc.h"
#include "../nde/ndestring.h"
#include "workorder.h"
#include <shlwapi.h>
#include "../nde/nde_c.h"
#include "VeritasPlay.h"
#include "MciPlay.h"
#include "../nu/ListView.h"
#include "../primo/obj_primo.h"
#include <api/service/waservicefactory.h>