//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ml_cloud.rc
//
#define IDS_CLOUD_SOURCES               1
#define IDS_SIGN_IN                     2
#define IDS_CLOUD_RESET                 3
#define IDHIDE                          3
#define IDR_CONTEXTMENUS                4
#define IDS_RESET_SUCCEEDED             4
#define IDS_RESET_FAILED                5
#define IDS_ERROR_MESSAGE_ALL           6
#define IDS_ERROR_MESSAGE_LESS          7
#define IDS_ERROR_MESSAGE_SLIM          8
#define IDS_REMOVE_ERROR_MESSAGE        9
#define IDS_NOT_SPECIFIED               10
#define IDS_N_A                         11
#define IDS_DEVICE_REMOVAL              12
#define IDS_FIRST_PULL_COMPLETED        13
#define IDS_CRITICAL_ERROR              14
#define IDS_INIT_DB                     15
#define IDS_CALCULATING_MEDIA_HASH      16
#define IDS_ANNOUNCE_METADATA           17
#define IDS_CALUCATING_MEDIA_HASH_FAILED 18
#define IDS_SET_IGNORE_FAILED           19
#define IDS_CALCULATING_MEDIA_HASH_FOR_FILES 20
#define IDS_PULLING                     21
#define IDS_WAITING_LOGIN               22
#define IDS_DEVICES_LIST                23
#define IDS_FIRST_PULL                  24
#define IDS_REFRESH_DEVICES_LIST        25
#define IDS_STARTING_BG_THREAD          26
#define IDS_METADATA_CHANGED            27
#define IDS_FROM_LIBRARY                28
#define IDS_EXTERNAL                    29
#define IDS_IGNORE_METADATA_CHANGE      30
#define IDS_ERROR_QUERYING_IGNORED      31
#define IDS_CLOUD_IGNORED_FILES         32
#define IDS_FILES_NOT_COMPATIBLE        33
#define IDS_CLEARED_LOGS                34
#define IDS_ERROR_CLEARING_LOGS         35
#define IDS_TIME                        36
#define IDS_MESSAGE                     37
#define IDS_CALUCATING_MEDIA_HASH_SKIPPED 38
#define IDS_FILEPATH                    39
#define IDS_RESET_LIBRARY_MESSAGE       40
#define IDS_UNABLE_DO_RESET             41
#define IDS_LOCAL_LIBRARY               42
#define IDS_RESET                       43
#define IDS_RESET_IGNORED_FAILED        44
#define IDS_RESET_IGNORED_MESSAGE       45
#define IDS_OPTIONS                     46
#define IDS_LOGGING                     47
#define IDS_EXCLUSIONS                  48
#define IDS_START_LOCAL_LIBRARY_RESCAN  49
#define IDS_UPDATING_LOCAL_DEVICE_NAME  50
#define IDS_NO_FILES_INCOMPATIBLE       51
#define IDS_FILES_NOT_COMPATIBLE_LOADING 52
#define IDS_ABORT_ADD_NEW_FILES         53
#define IDS_CHECKING_FOR_NEW_FILES      54
#define IDS_SCANNING_DETECTED_X_FILES   55
#define IDS_ADDING_X                    56
#define IDS_FOUND_X_FILES_TO_PROCESS    57
#define IDS_NO_NEW_FILES_FOUND          58
#define IDS_CHECKING_FOR_MISSING_REMOVED_FILES 59
#define IDS_FOUND_X_TO_REMOVE           60
#define IDS_UPDATING_LOCAL_DEVICE       61
#define IDS_RESTORE_STATUS_WINDOW       62
#define IDS_REMOVE_FROM_DEVICE          63
#define IDS_REMOVE_FROM_LOCAL_CLOUD_DEVICE 64
#define IDS_REMOVE_FROM_CLOUD_DEVICE    65
#define IDS_ADD_FAILED                  66
#define IDS_ADD_TO_CLOUD_DEVICE         67
#define IDS_STRING68                    68
#define IDS_UNABLE_DETERMINE_CLOUD_SOURCES 68
#define IDS_STATUS_NORMAL               69
#define IDS_STATUS_FIRST_PULL           70
#define IDS_STATUS_SCANNING             71
#define IDS_STATUS_CALCULATING_MEDIA_HASH 72
#define IDS_STATUS_PROCESSING_X_OF_X    73
#define IDS_FORCED_PULLING              74
#define IDS_FORCED_PULL_COMPLETED       75
#define IDS_ALL_FILES                   76
#define IDS_STATUS_WAITING_LOGIN        77
#define IDS_STATUS_NETWORK_FAILURE      78
#define IDS_CHECKING_FOR_MISSING_FILES_ONLY 79
#define IDS_DEV_MODE                    80
#define IDS_INCOMPATIBLE_FILES          81
#define IDS_RESET_IGNORED_FILES         82
#define IDS_UNAUTHORIZED                83
#define IDS_UNAUTHORIZED_LOG            84
#define IDS_GETTING_USER_PROFILE        85
#define IDS_CUSTOM_API_URL              86
#define IDS_CUSTOM_WEB_URL              87
#define IDS_GETTING_PLAYLISTS           88
#define IDS_REMOVE_PLAYLIST             89
#define IDS_ADD_PLAYLIST                90
#define IDS_QA_MODE                     91
#define IDS_STAGE_MODE                  92
#define IDS_ANNOUNCE_ALL_PLAYLISTS      93
#define IDS_ANNOUNCE_PARTIAL_PLAYLISTS  94
#define IDS_STRING95                    95
#define IDS_ADD_PL_TO_CLOUD             95
#define IDS_CLOUD_PL_REMOVAL            96
#define IDS_CLOUD_PL_REMOVAL_TITLE      97
#define IDS_UPDATE_PLAYLIST             98
#define IDS_CALCULATING_ALBUMART_HASH   99
#define IDS_ANNOUNCE_ALBUMART           100
#define IDD_DEBUG_CONSOLE               101
#define IDS_STATUS_CALCULATING_ALBUMART_HASH 101
#define IDD_UPLOAD_PROGRESS             102
#define IDD_STATUS_DIALOG               102
#define IDS_PLAYLISTS                   102
#define IDB_TREEITEM_CLOUD              103
#define IDD_DEBUG_CONSOLE1              103
#define IDS_ALREADY_ADDED               103
#define IDD_DEBUG_CONSOLE2              104
#define IDS_FINISHED_PL_UPDATES         104
#define IDD_DEBUG_CONSOLE3              105
#define IDS_ALWAYS_PROMPT               105
#define IDB_TREEITEM_SIGN_IN            106
#define IDD_DEBUG_CONSOLE4              106
#define IDS_KEEP_PLAYLIST               106
#define IDS_REMOVE_THE_PLAYLIST         107
#define IDS_CLOUD_ACCOUNT               108
#define IDS_CLOUD_ACCOUNT_USER          109
#define IDS_ADD_SOURCE                  110
#define IDS_WINAMP_ACCOUNT              111
#define IDS_VIEW                        112
#define IDC_MEDIAHASH                   1001
#define IDC_UPLOAD                      1002
#define IDC_REVISION                    1003
#define IDC_ADD                         1004
#define IDC_LOGFOLDER                   1005
#define IDC_LOGGING                     1006
#define IDC_LOGBINARY                   1007
#define IDC_RESET                       1008
#define IDC_CLEAR_LOGS                  1009
#define IDC_REFRESH                     1010
#define IDC_SAVE_LOG                    1011
#define IDC_STATUS                      1012
#define IDC_LIST1                       1013
#define IDC_LIST2                       1014
#define IDC_IGNORED                     1015
#define IDC_RESET_IGNORED               1016
#define IDC_LOGFAILEDONLY               1017
#define IDC_TAB1                        1018
#define IDC_LOGCLEARSTARTUP             1019
#define IDC_EXCLUDED_COUNT              1020
#define IDC_SET_NAME                    1021
#define IDC_CURRENT_NAME                1022
#define IDC_SHOW_LOCAL_DEVICE           1023
#define IDC_PROGRESS                    1024
#define IDC_RESCAN                      1025
#define IDC_NOT_LOGGED_IN               1026
#define IDC_LOGGED_IN                   1027
#define IDC_LOGIN_HERE                  1028
#define IDC_LOGIN_HERE2                 1029
#define IDC_MANAGE_HERE                 1030
#define IDC_HIDE                        1031
#define IDC_STATIC_SCANNING             1032
#define IDC_STATIC_FIRST_PULL           1033
#define IDC_STATUS_TEXT                 1034
#define IDC_STATUS_X_OF_X               1035
#define IDC_DEV_MODE                    1036
#define IDC_REMOVE_PL_MODE              1037
#define IDC_ADD_PL_TO_CLOUD             1038
#define IDC_CLOUD_ACCOUNT               1039
#define ID_NAVIGATION_PREFERENCES       40000
#define ID_SIGN_ACCOUNT                 40000
#define ID_NAVIGATION_HELP              40001
#define ID_SIGN_HELP                    40001
#define ID_SIGN_TOS                     40002
#define ID_NAVIGATION_TOGGLESTATUSWINDOW 40003
#define ID_NAVIGATION_SHOW              40009
#define IDS_NULLSOFT_CLOUD              65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
