#pragma once
#include "api.h"
#include <api/service/waservicefactory.h>
#include <api/service/services.h>
#include "MKVDecoder.h"
#include "flv_aac_decoder.h"
#include "nsvdec.h"
#include "CTDecoder.h"
#include "aacplusdec.h"
#include "../nu/Singleton.h"
