#ifndef NULLSOFT_DROPBOX_PLUGIN_EMBEDEDEDITCONTROL_HEADER
#define NULLSOFT_DROPBOX_PLUGIN_EMBEDEDEDITCONTROL_HEADER

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#include <windows.h>

typedef void (CALLBACK *EMBEDCONTROLCALLBACK)(HWND /*hEmbeded*/, DWORD /*exitCode*/);

BOOL EmbedEditControl(HWND hwndEdit, EMBEDCONTROLCALLBACK callback);

#endif // NULLSOFT_DROPBOX_PLUGIN_EMBEDEDEDITCONTROL_HEADER