#ifndef NULLSOFT_DROPBOX_PLUGIN_METAKEY_STORE_HEADER
#define NULLSOFT_DROPBOX_PLUGIN_METAKEY_STORE_HEADER

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#include <wtypes.h>

typedef WORD METAKEY;	

/**
	Default registered keys
**/

#define METAKEY_INVALID				0
#define METAKEY_TRACKARTIST			1
#define METAKEY_TRACKALBUM			2
#define METAKEY_TRACKTITLE			3
#define METAKEY_TRACKGENRE			4
#define METAKEY_TRACKCOMMENT			5
#define METAKEY_TRACKLENGTH			6
#define METAKEY_TRACKBITRATE			7
#define METAKEY_TRACKNUMBER			8
#define METAKEY_TRACKCOUNT			9
#define METAKEY_DISCNUMBER			10
#define METAKEY_DISCCOUNT			11
#define METAKEY_TRACKYEAR			12
#define METAKEY_TRACKPUBLISHER		13
#define METAKEY_TRACKCOMPOSER		14
#define METAKEY_ALBUMARTIST			15
#define METAKEY_FORMATTEDTITLE		16
#define METAKEY_TRACKBPM				17

#define METAKEY_TRACKARTIST_STRING		"TrackArtist"
#define METAKEY_TRACKALBUM_STRING		"TrackAlbum"
#define METAKEY_TRACKTITLE_STRING		"TrackTitle"
#define METAKEY_TRACKGENRE_STRING		"TrackGenre"
#define METAKEY_TRACKCOMMENT_STRING		"TrackComment"
#define METAKEY_TRACKLENGTH_STRING		"TrackLength"
#define METAKEY_TRACKBITRATE_STRING		"TrackBitrate"
#define METAKEY_TRACKNUMBER_STRING		"TrackNumber"
#define METAKEY_TRACKCOUNT_STRING		"TrackCount"
#define METAKEY_DISCNUMBER_STRING		"DiscNumber"
#define METAKEY_DISCCOUNT_STRING			"DiscCount"
#define METAKEY_TRACKYEAR_STRING			"TrackYear"
#define METAKEY_TRACKPUBLISHER_STRING	"TrackPublisher"
#define METAKEY_TRACKCOMPOSER_STRING		"TrackComposer"
#define METAKEY_ALBUMARTIST_STRING		"AlbumArtist"
#define METAKEY_FORMATTEDTITLE_STRING	"FormattedTitle"
#define METAKEY_TRACKBPM_STRING			"TrackBpm"

HRESULT RegisterMetaKey(LPCSTR pszKeyName, METAKEY *pMetaKeyOut);
HRESULT GetMetaKeyByName(LPCSTR pszKeyName, METAKEY *pMetaKeyOut);

#endif // NULLSOFT_DROPBOX_PLUGIN_METAKEY_STORE_HEADER