//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dropBox.rc
//
#define IDS_PLUGIN_DESCRIPTION_TEMPLATE 102
#define IDS_BUTTON_NEW_TITLE            103
#define IDS_BUTTON_OPEN_TITLE           104
#define IDR_ITEMVIEW_ACCELERATORS       104
#define IDS_BUTTON_SAVE_TITLE           105
#define IDR_DROPWINDOW_ACCELERATORS     105
#define IDS_FILE_ATTRIBUTES             106
#define IDS_FILETYPE_AUDIO              107
#define IDS_FILETYPE_VIDEO              108
#define IDS_FILETYPE_PLAYLIST           109
#define IDS_FILETYPE_FOLDER             110
#define IDS_FILETYPE_UNKNOWN            111
#define IDS_FILETYPE_MISSING            112
#define IDS_FILETYPE_LINK               113
#define IDS_FILETYPE_STREAM             114
#define IDS_FILETYPE_AUDIOCDTRACK       115
#define IDS_PLAYLIST_OPENDIALOGTITLE    116
#define IDS_PLAYLIST_SAVEDIALOGTITLE    117
#define IDS_ERROR_NOPLAYLISTMANAGER     118
#define IDS_ERROR_DOCUMENTLOAD          119
#define IDS_ERROR_DIALOGFAILED          120
#define IDS_ERROR_DOCUMENTCREATE        121
#define IDS_ERROR_UNKNOWN               122
#define IDS_ERROR_DOCUMENTSAVE          123
#define IDS_ERROR_OPENFAILED            124
#define IDS_DOCUMENT_CLOSEMODIFIED      125
#define IDS_DOCUMENT_CONFIRMCLOSE       126
#define IDS_ERROR_SAVEFAILED            127
#define IDS_FILEFILTER_ALLPLAYLIST      128
#define IDS_PLAYLIST                    129
#define IDI_DROPBOX                     129
#define IDS_FILEFILTER_ALLFILES         130
#define IDD_SAVEDLGEXTENSION            130
#define IDS_ERROR_BADPLAYLISTNAME       131
#define IDD_ASYNCOPERATION              131
#define IDS_PLAYLISTNAME_BADFORMAT      132
#define IDS_BUTTON_ABORT                133
#define IDD_RENAMEPLAYLIST              133
#define IDS_BUTTON_CANCEL               134
#define IDD_PREFERENCES_FRAME           134
#define IDS_BUTTON_CONTINUE             135
#define IDD_PREFPAGE_GENEREAL           135
#define IDD_PREFPAGE_VIEW               135
#define IDS_BUTTON_IGNORE               136
#define IDS_BUTTON_NO                   137
#define IDD_PREFPAGE_FILTER             137
#define IDS_BUTTON_OK                   138
#define IDD_PROFILESELECTOR             138
#define IDD_PROFILEUI                   138
#define IDS_BUTTON_RETRY                139
#define IDD_INSERTFILTER                139
#define IDS_BUTTON_TRYAGAIN             140
#define IDD_PREFERENCES_SHORTCUT        140
#define IDS_BUTTON_YES                  141
#define IDD_PREFPAGE_GENERAL            141
#define IDS_BUTTON_RELOAD               142
#define IDD_SIMPLEVIEW_EDITOR           142
#define IDS_BUTTON_SAVE                 143
#define IDD_PREFVIEW_EMPTY              143
#define IDS_BUTTON_DISCARD              144
#define IDD_PROFILEUI_EMPTY             144
#define IDS_BUTTON_HELP                 145
#define IDS_UNKNOWN                     146
#define IDS_REGISTER_PLAYLIST           147
#define IDS_REPLACE_EXISTING_FILE       148
#define IDS_DOCUMENT_MODIFIEDOUTSIDE    149
#define IDS_ERROR_UNKNOWN_PLAYLISTWRITER 150
#define IDS_DOCUMENT_CONFIRMRELOAD      151
#define IDS_ERROR_UNKNOWN_PLAYLISTLOADER 152
#define IDS_ERROR_PLAYLIST_FILENOTFOUND 153
#define IDS_DEFAULT_WINDOWNAME          154
#define IDS_EMPTYLIST_MESSAGE           155
#define IDS_ASYNCOP_INSERT              156
#define IDS_PROCESSED_PERCENT           157
#define IDS_PROCESSED_ITEMS             158
#define IDS_ASYNCOP_ORDER               159
#define IDS_SELECT_PROFILE              160
#define IDS_MORE                        161
#define IDS_DROPBOX                     162
#define IDS_PREFPAGE_VIEW               163
#define IDS_PREFPAGE_FILTER             164
#define IDS_PREFPAGE_Advanced           165
#define IDS_PREFPAGE_ADVANCED           165
#define IDS_MODIFY                      165
#define IDS_AUDIOCDTRACK_EXTENSION_FAMILY 166
#define IDS_LINKFILE_EXTENSION_FAMILY   167
#define IDS_FILTERPOLICY_RULE_ASK       168
#define IDS_FILTERPOLICY_RULE_ADD       169
#define IDS_FILTERPOLICY_RULE_IGNORE    170
#define IDS_FILTERPOLICY_RULE_ENUMERATE 171
#define IDS_PROFILE_AUDIO               172
#define IDS_PROFILE_DATA                173
#define IDS_BUTTON_ADD                  174
#define IDS_BUTTON_ENUMERATE            175
#define IDS_DOCUMENT_CHOOSEINSERTRULE   176
#define IDS_PREFERENCES_SHORTCUT        177
#define IDS_PREFPAGE_GENERAL            178
#define IDS_SIMPLEVIEW                  179
#define IDS_SIMPLEVIEW_DESCRIPTION      180
#define IDS_DETAILSVIEW                 181
#define IDS_DETAILSVIEW_DESCRIPTION     182
#define IDS_LINK_CREATE                 183
#define IDS_LINK_DELETE                 184
#define IDS_LINK_DUPLICATE              185
#define IDS_PREFPAGE_FILTER_DESC        186
#define IDS_PREFPAGE_VIEW_DESC          187
#define IDS_PREFPAGE_GENERAL_DESC       188
#define IDS_RESTART_WINDOW              189
#define IDS_PROFILE_NEW                 190
#define IDS_PROFILE_NEW_DESCRIPTION     191
#define IDS_PROFILE_COPY_PREFIX         192
#define IDS_PROFILE_DELETE_TITLE        193
#define IDS_PROFILE_DELETE              194
#define IDS_BUTTON_DELETE               195
#define IDS_PROFILE_COMBOBOX_EMPTY      196
#define IDS_PREFVIEW_EMPTY              197
#define IDS_PROFILEUI_EMPTY_MESSAGE     198
#define IDS_PROFILE_AUDIO_DESCRIPTION   199
#define IDS_COLUMN_FORMATTEDTITLE       200
#define IDS_COLUMN_FILEPATH             201
#define IDS_COLUMN_FILENAME             202
#define IDS_COLUMN_FILESIZE             203
#define IDS_COLUMN_FILETYPE             204
#define IDS_COLUMN_FILEEXTENSION        205
#define IDS_COLUMN_FILEMODIFIED         206
#define IDS_COLUMN_FILECREATED          207
#define IDS_COLUMN_FILEATTRIBUTES       208
#define IDS_COLUMN_TRACKARTIST          209
#define IDS_COLUMN_TRACKALBUM           210
#define IDS_COLUMN_TRACKTITLE           211
#define IDS_COLUMN_TRACKGENRE           212
#define IDS_COLUMN_TRACKLENGTH          213
#define IDS_COLUMN_TRACKBITRATE         214
#define IDS_COLUMN_TRACKNUMBER          215
#define IDS_COLUMN_DISCNUMBER           216
#define IDS_COLUMN_TRACKYEAR            217
#define IDS_COLUMN_TRACKPUBLISHER       218
#define IDS_COLUMN_TRACKCOMPOSER        219
#define IDS_COLUMN_ALBUMARTIST          220
#define IDS_COLUMN_TRACKCOMMENT         221
#define IDS_COLUMN_TRACKBPM             222
#define IDS_COLUMN_EXTENSIONFAMILY      223
#define IDS_PROFILE_DATA_DESCRIPTION    224
#define IDS_PROFILES_ASK                225
#define IDS_PROFILES_ASK_DESCRIPTION    226
#define IDS_TOOLBUTTON_PLAY             227
#define IDS_TOOLBUTTON_ENQUEUE          228
#define IDS_TOOLBUTTON_PLAY_DESC        229
#define IDS_COLUMN_FORMATTEDTITLE_LONG  230
#define IDS_COLUMN_FILEPATH_LONG        231
#define IDS_COLUMN_FILENAME_LONG        232
#define IDS_COLUMN_FILESIZE_LONG        233
#define IDS_COLUMN_FILETYPE_LONG        234
#define IDS_COLUMN_FILEEXTENSION_LONG   235
#define IDS_COLUMN_FILEMODIFIED_LONG    236
#define IDS_COLUMN_FILECREATED_LONG     237
#define IDS_COLUMN_FILEATTRIBUTES_LONG  238
#define IDS_COLUMN_TRACKARTIST_LONG     239
#define IDS_COLUMN_TRACKALBUM_LONG      240
#define IDS_COLUMN_TRACKTITLE_LONG      241
#define IDS_COLUMN_TRACKGENRE_LONG      242
#define IDS_COLUMN_TRACKLENGTH_LONG     243
#define IDS_COLUMN_TRACKBITRATE_LONG    244
#define IDS_COLUMN_TRACKNUMBER_LONG     245
#define IDS_COLUMN_DISCNUMBER_LONG      246
#define IDS_COLUMN_TRACKYEAR_LONG       247
#define IDS_COLUMN_TRACKPUBLISHER_LONG  248
#define IDS_COLUMN_TRACKCOMPOSER_LONG   249
#define IDS_COLUMN_ALBUMARTIST_LONG     250
#define IDS_COLUMN_TRACKCOMMENT_LONG    251
#define IDS_COLUMN_TRACKBPM_LONG        252
#define IDS_COLUMN_EXTENSIONFAMILY_LONG 253
#define IDS_TOOLBUTTON_ENQUEUE_DESC     254
#define IDS_TOOLBUTTON_REORDER          255
#define IDS_TOOLBUTTON_REORDER_DESC     256
#define IDS_TOOLBUTTON_DELETE           257
#define IDS_TOOLBUTTON_DELETE_DESC      258
#define IDS_TOOLBUTTON_NEWPL            259
#define IDS_TOOLBUTTON_NEWPL_DESC       260
#define IDS_TOOLBUTTON_OPENPL           261
#define IDS_TOOLBUTTON_OPENPL_DESC      262
#define IDS_TOOLBUTTON_SAVEPL           263
#define IDS_TOOLBUTTON_SAVEPL_DESC      264
#define IDS_DOCUMENTNAME_PREFIX         265
#define IDC_CHECK_REGISTERPLAYLIST      1008
#define IDC_LABEL_TITLE                 1011
#define IDC_LABEL_PROCESSED             1012
#define IDC_EDIT1                       1014
#define IDC_EDIT_NAME                   1014
#define IDC_PROFILELIST_FRAME           1014
#define IDC_TABFRAME                    1015
#define IDC_EDIT_PATH                   1015
#define IDC_EDIT_DESCRIPTION            1015
#define IDC_LIST1                       1016
#define IDC_FILTERLIST                  1016
#define IDC_TITLE                       1017
#define IDC_RADIO1                      1019
#define IDC_RADIO2                      1020
#define IDC_COMBO_SELECTPROFILE         1020
#define IDC_RADIO3                      1021
#define IDC_BUTTON_MANAGEPROFILES       1021
#define IDC_PROFILELIST                 1023
#define IDC_LABEL_GREETING              1024
#define IDC_BUTTON_ENUMERATE            1029
#define IDC_CHECK_APPLYTOALL            1031
#define IDC_BUTTON_ADD                  1032
#define IDC_BUTTON_IGNORE               1033
#define IDC_MESSAGEICON                 1034
#define IDC_MESSAGETITLE                1035
#define IDC_CHECK_SHORTCUT              1036
#define IDC_LABEL_DEFAULT_PROFILE       1042
#define IDC_PROFILEVIEW_RECT            1045
#define IDC_LABEL_SHORTCUT_HELP         1050
#define IDC_LABEL_SHORTCUT              1051
#define IDC_BUTTON_NAME_RESET           1054
#define IDC_BUTTON_NAME_UPDATE          1055
#define IDC_BUTTON_DESCRIPTION_RESET    1058
#define IDC_BUTTON_DESCRIPTION_UPDATE   1059
#define IDC_CHECK1                      1060
#define IDC_CHECK_INDEX                 1060
#define IDC_CHECK2                      1061
#define IDC_CHECK_ICON                  1061
#define IDC_CHECK3                      1062
#define IDC_CHECK_DETAILS               1062
#define IDC_BUTTON_CREATE               1064
#define IDC_EDIT3                       1065
#define IDC_BUTTON_DELETE               1065
#define IDC_BUTTON3                     1066
#define IDC_BUTTON_DUPLICATE            1066
#define IDC_BUTTON1                     1066
#define IDC_BUTTON_ADVANCED             1066
#define IDC_BUTTON_LOAD                 1067
#define IDC_LABEL_MESSAGE               1068
#define IDC_COMBO1                      1071
#define IDC_COMBO_COLUMN                1071
#define IDC_LABEL_INDEX                 1072
#define IDC_LABEL_ICON                  1073
#define IDC_LABEL_DETAILS               1074
#define IDR_DEFAULTPLAYLIST_IMAGE       10000
#define IDR_SMALLFILETYPES_IMAGE        10001
#define IDR_MENU_DROPWINDOW             10002
#define IDR_NUMHOLDERIMAGE              10003
#define IDR_PROGRESSCIRCLE_IMAGE        10004
#define IDR_DRAGIMAGE                   10005
#define IDR_TOOLBAR_IMAGE               10006
#define IDR_OPENPLAYLIST_IMAGE          10007
#define IDR_SIMPLEVIEW_PREVIEWIMAGE     10008
#define IDR_DETAILSVIEW_PREVIEWIMAGE    10009
#define IDR_GROUPHEADER_IMAGE           10010
#define IDR_WARNING_SMALL_IMAGE         10011
#define IDR_MENUBUTTON_IMAGE            10012
#define ID_COPY                         40001
#define ID_CUT                          40002
#define ID_PASTE                        40003
#define ID_DELETE                       40004
#define ID_COPYWIN                      40005
#define ID_PASTEWIN                     40006
#define ID_CUTWIN                       40007
#define ID_SELECTALL                    40008
#define ID_INVERTSELECTION              40010
#define ID_DOCUMENT_NEW                 40012
#define ID_DOCUMENT_OPEN                40013
#define ID_DOCUMENT_SAVE                40014
#define ID_WINDOW_CONTEXTMENU           40016
#define ID_WINDOW_CLOSE                 40024
#define ID_DOCUMENT_SAVEAS              40035
#define ID_DOCUMENT_RENAME              40036
#define ID_IMPORT_FILES                 40044
#define ID_IMPORT_FOLDER                40045
#define ID_IMPORT_CURRENTPLAYLIST       40046
#define ID_SIMPLEVIEW_SHOWINDEX         40047
#define ID_SIMPLEVIEW_SHOWTYPEICON      40048
#define ID_SIMPLEVIEW_RIGHTCOLUMN_LENGTH 40049
#define ID_SIMPLEVIEW_RIGHTCOLUMN_SIZE  40050
#define ID_SIMPLEVIEW_RIGHTCOLUMN_NONE  40053
#define ID_SIMPLEVIEW_RIGHTCOLUMN_EXTENSION 40054
#define ID_ORDER_ASCENDING              40062
#define ID_ITEMCONTEXT_                 40073
#define ID_Menu40074                    40074
#define ID_PLAY                         40076
#define ID_ENQUEUE                      40077
#define ID_REVERSEORDER                 40078
#define ID_SELECTIONCONTEXT             40079
#define ID_SHOWFILEINFO                 40080
#define ID_ACTION                       40086
#define ID_EXPLOREFOLDER                40089
#define ID_PLUGIN_PREFERENCES           40096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40100
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
