!ifndef NULLSOFT_WINAMP_UNINSTALLER_SECTION_DESCRIPTION_TABLE_HEADER
!define NULLSOFT_WINAMP_UNINSTALLER_SECTION_DESCRIPTION_TABLE_HEADER

!include ".\utils\sectionDescription.nsh"

${UNINSTALL_DESCRIPTION_TABLE_BEGIN}
	${DESCRIPTION} IDX_UNINSTALL_COMPONENTS_GROUP		$(IDS_UNINSTALL_COMPONENTS_GROUP_DESC)
	${DESCRIPTION} IDX_UNINSTALL_MEDIA_PLAYER			$(IDS_UNINSTALL_MEDIA_PLAYER_DESC)
	${DESCRIPTION} IDX_UNINSTALL_USER_PREFERENCES		$(IDS_UNINSTALL_USER_PREFERENCES_DESC)
		
	${DESCRIPTION} IDX_UNINSTALL_BUNDLES_GROUP			$(IDS_UNINSTALL_BUNDLES_GROUP_DESC)
	${DESCRIPTION} IDX_UNINSTALL_WINAMP_TOOLBAR			$(IDS_UNINSTALL_WINAMP_TOOLBAR_DESC)
	${DESCRIPTION} IDX_UNINSTALL_WINAMP_REMOTE			$(IDS_UNINSTALL_WINAMP_REMOTE_DESC)
	${DESCRIPTION} IDX_UNINSTALL_BROWSER_PLUGIN			$(IDS_UNINSTALL_BROWSER_PLUGIN_DESC)
	${DESCRIPTION} IDX_UNINSTALL_EMUSIC					$(IDS_UNINSTALL_EMUSIC_DESC)
	
${DESCRIPTION_TABLE_END}

!endif ;NULLSOFT_WINAMP_UNINSTALLER_SECTION_DESCRIPTION_TABLE_HEADER